### ISSUE TITLE
Expanding Gem publishers

### ISSUE THREAD

**Issue by seancribbs** [seancribbs/webmachine-ruby#204]
I've come to realize that I shouldn't be the only one able to publish the Webmachine gem. I'd like to open it up to long-time committers so that the project can move forward without me being in the way.

I suggest @lgierth be one of them. Other contributors, I welcome your votes on the matter.

**Comment by seancribbs** [comment]
Added Lars. I'd like at least one other. Volunteers?

**Comment by bethesque** [comment]
I'm up for it if you'll have me. I :heart:  webmachine.

**Comment by seancribbs** [comment]
@bethesque You got it. You're registered on Rubygems?

**Comment by bethesque** [comment]
Yup, I'll email you my email address when I work out which one it is.

**Comment by seancribbs** [comment]
Thanks! I tried a few from the git history with no luck.

**Comment by seancribbs** [comment]
Done, thanks!

**Comment by kgish** [comment]
I'd like to volunteer to help out also, though I still have a ways to go ...
